### ISSUE TITLE
Ability to adjust styling to be more finely grained

### ISSUE THREAD

**Issue by Awethentique** [exzos28/react-native-qrcode-svg#3]
Thank you for the great work and effort you have put into this. I know this is a big ask, but I am willing to be able to contribute to making this a really great library for everyone

I am looking for the ability to style the QR codes according to the options available on https://www.qrcode-monkey.com/

![Screenshot 2024-03-14 at 03 34 37](https://github.com/exzos28/react-native-qr-svg/assets/1106670/a3e1623b-d654-4179-ba78-b3a7890b4526)

- be able to adjust the roundedness of the dots and lines
- allow gradient fills in the colors

**Comment by exzos28** [comment]
Hello, sure, I'll do it.
Anyway, the repository is open to contribution.

**Comment by Awethentique** [comment]
Hi Alex, thank your for your response. As far as QR code and algorithms, I
am terrible at that and math. However I do have expertise in design,
styling and building front ends.

I would be happy to assist

Ritesh Makan
Whatsapp: +44 7591 099112

**Comment by exzos28** [comment]
Hello! 
Sorry for the long reply.
I did this, since version 1.2.0 I added the ability to pass the gradientColors and gradientProps properties to define the gradient fill.

I also worked on the renderer, you can find the renderer property to define your own renderer. You can find examples of existing ones in renderers.ts file.
